(function () {
  'use strict';

  // Generated by tools/generate_minigame_catalog.py. Do not edit manually.
  window.LivelySamMinigameCatalog = Object.freeze({
  "version": 3,
  "generatedAt": "2026-04-19T12:32:08Z",
  "games": [
    {
      "id": "dino-run-1",
      "seriesId": "dino-run",
      "seriesTitle": "Dino Run",
      "seriesDescription": "기본, 확장, 하드 모드를 순서대로 즐길 수 있습니다.",
      "seriesIcon": "🦖",
      "title": "Dino Run",
      "icon": "🦖",
      "status": "ready",
      "launchType": "iframe",
      "entry": "js/minigames/games/DinoRun1.html",
      "description": "기본 규칙으로 달리는 클래식 Dino Run입니다.",
      "scoreLabel": "생존 점수",
      "rankingLabel": "Firebase Firestore 명예의 전당",
      "leaderboardMode": "personal-best",
      "tags": [
        "firebase",
        "hall-of-fame"
      ]
    },
    {
      "id": "dino-run-2",
      "seriesId": "dino-run",
      "seriesTitle": "Dino Run",
      "seriesDescription": "기본, 확장, 하드 모드를 순서대로 즐길 수 있습니다.",
      "seriesIcon": "🦖",
      "title": "Dino Run 2",
      "icon": "🦕",
      "status": "ready",
      "launchType": "iframe",
      "entry": "js/minigames/games/DinoRun2.html",
      "description": "장애물 패턴이 확장된 Dino Run 2입니다.",
      "scoreLabel": "생존 점수",
      "rankingLabel": "Firebase Firestore 명예의 전당",
      "leaderboardMode": "personal-best",
      "tags": [
        "firebase",
        "hall-of-fame"
      ]
    },
    {
      "id": "dino-run-hard",
      "seriesId": "dino-run",
      "seriesTitle": "Dino Run",
      "seriesDescription": "기본, 확장, 하드 모드를 순서대로 즐길 수 있습니다.",
      "seriesIcon": "🦖",
      "title": "Dino Run Hard",
      "icon": "🌋",
      "status": "ready",
      "launchType": "iframe",
      "entry": "js/minigames/games/DinoRunHard.html",
      "description": "속도와 장애물이 강화된 하드 모드입니다.",
      "scoreLabel": "하드 모드 점수",
      "rankingLabel": "Firebase Firestore 명예의 전당",
      "leaderboardMode": "personal-best",
      "tags": [
        "firebase",
        "hall-of-fame",
        "hard"
      ]
    },
    {
      "id": "wing-tap-1",
      "seriesId": "wing-tap",
      "seriesTitle": "Wing Tap",
      "seriesDescription": "기본, 확장, 보스전을 한 흐름으로 즐길 수 있습니다.",
      "seriesIcon": "🐥",
      "title": "Wing Tap Classic",
      "icon": "🐥",
      "status": "ready",
      "launchType": "iframe",
      "entry": "js/minigames/games/WingTap1.html",
      "description": "기본 조작으로 즐기는 클래식 Wing Tap입니다.",
      "scoreLabel": "비행 점수",
      "rankingLabel": "Firebase Firestore 명예의 전당",
      "leaderboardMode": "personal-best",
      "tags": [
        "firebase",
        "hall-of-fame"
      ]
    },
    {
      "id": "wing-tap-2",
      "seriesId": "wing-tap",
      "seriesTitle": "Wing Tap",
      "seriesDescription": "기본, 확장, 보스전을 한 흐름으로 즐길 수 있습니다.",
      "seriesIcon": "🐥",
      "title": "Wing Tap 2",
      "icon": "🐤",
      "status": "ready",
      "launchType": "iframe",
      "entry": "js/minigames/games/WingTap2.html",
      "description": "난이도와 장애물이 강화된 확장 비행 모드입니다.",
      "scoreLabel": "비행 점수",
      "rankingLabel": "Firebase Firestore 명예의 전당",
      "leaderboardMode": "personal-best",
      "tags": [
        "firebase",
        "hall-of-fame"
      ]
    },
    {
      "id": "ocean-tap",
      "seriesId": "ocean-tap",
      "seriesTitle": "OceanTap",
      "seriesDescription": "수중 터널을 통과하는 바다 아케이드 시리즈입니다.",
      "seriesIcon": "🦈",
      "title": "OceanTap",
      "icon": "🦈",
      "status": "ready",
      "launchType": "iframe",
      "entry": "js/minigames/games/OceanTap.html",
      "description": "상어처럼 헤엄치며 이어지는 수중 터널을 통과하는 OceanTap입니다.",
      "scoreLabel": "수영 점수",
      "rankingLabel": "Firebase Firestore 명예의 전당",
      "leaderboardMode": "all-scores",
      "tags": [
        "firebase",
        "hall-of-fame",
        "ocean",
        "arcade"
      ],
      "hallNotice": "개인당 최고 점수 3개를 기록합니다."
    },
    {
      "id": "wing-boss",
      "seriesId": "wing-tap",
      "seriesTitle": "Wing Tap",
      "seriesDescription": "기본, 확장, 보스전을 한 흐름으로 즐길 수 있습니다.",
      "seriesIcon": "🐥",
      "title": "Wing Boss",
      "icon": "🦅",
      "status": "ready",
      "launchType": "iframe",
      "entry": "js/minigames/games/WingBoss.html",
      "description": "보스 패턴 중심의 전투 비행 모드입니다.",
      "scoreLabel": "보스전 점수",
      "rankingLabel": "Firebase Firestore 명예의 전당",
      "leaderboardMode": "personal-best",
      "tags": [
        "firebase",
        "hall-of-fame",
        "boss"
      ]
    },
    {
      "id": "parcel-stack",
      "seriesId": "parcel-stack",
      "seriesTitle": "Parcel Stack",
      "seriesDescription": "정확한 타이밍으로 상자를 쌓는 적재 게임입니다.",
      "seriesIcon": "📦",
      "title": "Parcel Stack",
      "icon": "📦",
      "status": "ready",
      "launchType": "iframe",
      "entry": "js/minigames/games/ParcelStack.html",
      "description": "움직이는 상자를 카트 위에 최대한 안정적으로 쌓아 올립니다.",
      "scoreLabel": "적재 점수",
      "rankingLabel": "Firebase Firestore 명예의 전당",
      "leaderboardMode": "all-scores",
      "tags": [
        "firebase",
        "hall-of-fame",
        "new"
      ],
      "hallNotice": "개인당 최고 점수 3개를 기록합니다."
    },
    {
      "id": "lane-dash",
      "seriesId": "lane-dash",
      "seriesTitle": "Lane Dash",
      "seriesDescription": "짧게 반복 플레이하기 좋은 3레인 회피 액션입니다.",
      "seriesIcon": "🚗",
      "title": "Lane Dash",
      "icon": "🚗",
      "status": "ready",
      "launchType": "iframe",
      "entry": "js/minigames/games/LaneDash.html",
      "description": "차선을 바꾸며 장애물을 피하고 코인을 모으는 질주 게임입니다.",
      "scoreLabel": "질주 점수",
      "rankingLabel": "Firebase Firestore 명예의 전당",
      "leaderboardMode": "all-scores",
      "tags": [
        "firebase",
        "hall-of-fame",
        "new"
      ],
      "hallNotice": "개인당 최고 점수 3개를 기록합니다."
    }
  ]
});
})();
